version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 10
  reviewers:
  - "reload/developers"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 10
  reviewers:
  - "reload/developers"
