workflows:
  version: 2
  test:
    jobs:
      - test-5.6
      - test-7.0
      - test-7.1
      - test-7.2

shared: &test
  docker:
    - image: docker
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build container
        command: |
          docker build --file=Dockerfile-${PHP_VERSION} -t sut:latest .
    - run:
        name: Test
        command: |
          cid=$(docker create sut:latest)
          docker start $cid
          # Validate our configuration. Provide some time to allow PHP-FPM to start up
          docker exec $cid goss -g /goss/goss.yaml validate --retry-timeout 15s --sleep 1s
          # If we are valid we should also be healthy
          health=$(docker inspect --format='{{.State.Health.Status}}' $cid)
          echo $health | grep "healthy"
version: 2
jobs:
  test-5.6:
    <<: *test
    environment:
      PHP_VERSION: "5.6"
  test-7.0:
    <<: *test
    environment:
      PHP_VERSION: "7.0"
  test-7.1:
    <<: *test
    environment:
      PHP_VERSION: "7.1"
  test-7.2:
    <<: *test
    environment:
      PHP_VERSION: "7.2"
