workflows:
  version: 2
  test:
    jobs:
      - test-5.6
      - test-7.0
      - test-7.1
      - test-7.2

shared: &test
  docker:
    # Small image which has the key software we need: Docker and Dgoss (or curl needed to instal Dgoss)
    - image: kiwicom/dgoss
  steps:
    - checkout
    - run: apk --update add git
    - run: git clean -fd
    - setup_remote_docker
    - run:
        name: Build image
        command: docker build --file=Dockerfile-${PHP_VERSION} -t docker-drupal-php7-fpm:sut .
    - run:
        name: Test
        command: |
          # Needed to work with remote docker - see https://github.com/aelsabbahy/goss/pull/271
          export GOSS_FILES_STRATEGY=cp
          # Sleep a bit to ensure that PHP-FPM has time to start up.
          GOSS_SLEEP=15 dgoss run -e GOSS_PHP_VERSION="${PHP_VERSION}" docker-drupal-php7-fpm:sut

version: 2
jobs:
  test-5.6:
    <<: *test
    environment:
      PHP_VERSION: "5.6"
  test-7.0:
    <<: *test
    environment:
      PHP_VERSION: "7.0"
  test-7.1:
    <<: *test
    environment:
      PHP_VERSION: "7.1"
  test-7.2:
    <<: *test
    environment:
      PHP_VERSION: "7.2"
