#!/bin/bash
# Start FPM using php.ini in /etc/php/7.0/fpm/ using php-fpm.conf from same
# dir (which will in part include pool-configurations from
# /etc/php/7.0/fpm/pool.d) and force the process to stay in the foreground.
/usr/sbin/php-fpm7.0 -c /etc/php/7.0/fpm/ -y /etc/php/7.0/fpm/php-fpm.conf -F
