name: Lint
on: pull_request

jobs:
  markdownlint:
    name: markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run markdownlint
      uses: actionshub/markdownlint@main
