on: pull_request
name: Run Goss tests

jobs:
  php-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.php-versions.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Lookup PHP versions from Dockerfile-* names
      run: echo ::set-output name=matrix::$(ls Dockerfile-* | cut -c 12- | jq --raw-input --slurp 'split("\n") | map(select(. != ""))')
      id: php-versions
  goss_test:
    name: Goss test
    runs-on: ubuntu-latest
    needs: php-versions
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJSON(needs.php-versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v2
    - name: Run hadolint
      uses: brpaz/hadolint-action@v1.3.1
      with:
        dockerfile: Dockerfile-${{ matrix.php }}
    - uses: e1himself/goss-installation-action@v1.0.3
    - name: Build image
      run: |
        docker build --file=Dockerfile-${{ matrix.php }} -t docker-drupal-php7-fpm:sut .
    - name: Test image
      run: |
        # Sleep a bit to ensure that PHP-FPM has time to start up.
        GOSS_SLEEP=15 dgoss run -e GOSS_PHP_VERSION="${{ matrix.php }}" docker-drupal-php7-fpm:sut

