name: Anchore Container Vulnerability Scan
on: [push]
jobs:
  php-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.php-versions.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Lookup PHP versions from Dockerfile-* names
      run: echo ::set-output name=matrix::$(ls Dockerfile-* | cut -c 12- | jq --raw-input --slurp 'split("\n") | map(select(. != ""))')
      id: php-versions
  build:
    runs-on: ubuntu-latest
    needs: php-versions
    strategy:
      matrix:
        php: ${{ fromJSON(needs.php-versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-${{ matrix.php }}
        builder: ${{ steps.buildx.outputs.name }}
        tags: "reload/drupal-php7-fpm:${{ matrix.php }}"
        push: false
    - name: Anchore Container Vulnerability Scan
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "reload/drupal-php7-fpm:${{ matrix.php }}"
        acs-report-enable: true
    - name: Include PHP version in SARIF report
      if: ${{ always() }}
      run: |
        sed -i.bak -e 's|"fullyQualifiedName": "dockerfile"|"fullyQualifiedName": "Dockerfile-${{ matrix.php }}"|g' ${{ steps.scan.outputs.sarif }}
        sed -i.bak -e 's|"name": "Anchore Container Vulnerability Report (T0)"|"name": "Anchore (Dockerfile-${{ matrix.php }})"|g' ${{ steps.scan.outputs.sarif }}
    - name: Upload Anchore Container Vulnerability Scan SARIF report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
